/**
 * Excel AI Assistant - Recipe Service
 * Templates & Recipes system for reusable Excel workflows
 * 
 * @module services/recipeService
 */

import { logger } from '../utils/logger';

// ============================================================================
// Type Definitions
// ============================================================================

/** A recipe is a reusable template for Excel operations */
export interface Recipe {
  id: string;
  name: string;
  description: string;
  category: RecipeCategory;
  tags: string[];
  prompt: string;
  expectedInputs: RecipeInput[];
  previewImage?: string;
  author: string;
  authorId?: string;
  rating: number;
  ratingCount: number;
  usageCount: number;
  createdAt: Date;
  updatedAt: Date;
  version: string;
  isBuiltIn: boolean;
  isPublic: boolean;
  difficulty: "beginner" | "intermediate" | "advanced";
  estimatedTime?: string;
}

/** Recipe categories for organization */
export type RecipeCategory =
  | "data-cleaning"
  | "reporting"
  | "analysis"
  | "formatting"
  | "financial"
  | "dashboard"
  | "import-export"
  | "automation"
  | "custom";

/** Input parameter for a recipe */
export interface RecipeInput {
  name: string;
  type: "text" | "number" | "range" | "column" | "table" | "boolean" | "select" | "multi-select";
  required: boolean;
  label: string;
  description?: string;
  defaultValue?: any;
  options?: string[]; // For select/multi-select types
  validation?: InputValidation;
}

/** Input validation rules */
export interface InputValidation {
  min?: number;
  max?: number;
  pattern?: string;
  message?: string;
}

/** Filters for recipe search */
export interface RecipeFilters {
  category?: RecipeCategory;
  tags?: string[];
  search?: string;
  author?: string;
  difficulty?: "beginner" | "intermediate" | "advanced";
  minRating?: number;
  isBuiltIn?: boolean;
  sortBy?: "popular" | "newest" | "rating" | "name";
}

/** Result of executing a recipe */
export interface RecipeExecutionResult {
  success: boolean;
  message: string;
  actions?: RecipeAction[];
  error?: string;
  executionTime?: number;
}

/** Actions generated by recipe execution */
export interface RecipeAction {
  type: "insert_formula" | "set_values" | "create_chart" | "create_table" | "format_cells" | "add_validation" | "apply_conditional_formatting";
  description: string;
  target?: string;
  payload: any;
}

/** User's saved recipe with customizations */
export interface UserRecipe extends Recipe {
  originalRecipeId?: string;
  customizations?: Record<string, any>;
  lastUsed?: Date;
  useCount: number;
}

/** Recipe rating submitted by user */
export interface RecipeRating {
  recipeId: string;
  userId: string;
  rating: number;
  comment?: string;
  createdAt: Date;
}

/** Recipe execution history */
export interface RecipeExecution {
  recipeId: string;
  recipeName: string;
  executedAt: Date;
  inputs: Record<string, any>;
  result: RecipeExecutionResult;
  workbookName?: string;
}

// ============================================================================
// Built-in Recipes
// ============================================================================

const builtInRecipes: Recipe[] = [
  {
    id: "builtin-001",
    name: "Monthly Sales Report",
    description: "Create a comprehensive monthly sales report with summary table, trend chart, and pivot table by region",
    category: "reporting",
    tags: ["sales", "report", "monthly", "pivot-table", "chart"],
    prompt: `Create a monthly sales report with the following components:
1. Summary table with total sales, average order value, and transaction count
2. Line chart showing daily sales trend
3. Pivot table summarizing sales by region and product category
4. Top 10 products by revenue
5. Format numbers as currency
6. Add conditional formatting to highlight above-average days`,
    expectedInputs: [
      { name: "dataRange", type: "table", required: true, label: "Sales Data Range", description: "Select your sales data table (should include Date, Product, Region, Amount columns)" },
      { name: "month", type: "select", required: true, label: "Report Month", description: "Select the month for this report", options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] },
      { name: "currency", type: "select", required: false, label: "Currency", defaultValue: "USD", options: ["USD", "EUR", "GBP", "JPY", "CAD"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.8,
    ratingCount: 156,
    usageCount: 2340,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "5 min"
  },
  {
    id: "builtin-002",
    name: "Data Cleaning Wizard",
    description: "Clean messy data by removing duplicates, fixing dates, trimming whitespace, and standardizing formats",
    category: "data-cleaning",
    tags: ["cleaning", "duplicates", "dates", "formatting", "trim"],
    prompt: `Clean the selected dataset by:
1. Removing duplicate rows
2. Converting text dates to proper date format
3. Trimming whitespace from text columns
4. Standardizing text case (Title Case for names)
5. Removing special characters from phone numbers
6. Validating email formats
7. Creating a log of changes made`,
    expectedInputs: [
      { name: "dataRange", type: "table", required: true, label: "Data to Clean", description: "Select the data range you want to clean" },
      { name: "removeDuplicates", type: "boolean", required: false, label: "Remove Duplicates", defaultValue: true },
      { name: "fixDates", type: "boolean", required: false, label: "Fix Date Formats", defaultValue: true },
      { name: "trimText", type: "boolean", required: false, label: "Trim Whitespace", defaultValue: true },
      { name: "standardizeCase", type: "select", required: false, label: "Text Case Style", defaultValue: "none", options: ["none", "UPPERCASE", "lowercase", "Title Case"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.9,
    ratingCount: 289,
    usageCount: 5120,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "beginner",
    estimatedTime: "3 min"
  },
  {
    id: "builtin-003",
    name: "Financial Dashboard",
    description: "Build a 3-statement financial model with income statement, balance sheet, and cash flow",
    category: "financial",
    tags: ["finance", "dashboard", "income-statement", "balance-sheet", "cash-flow"],
    prompt: `Create a comprehensive financial dashboard:
1. Income Statement with revenue, COGS, gross profit, operating expenses, and net income
2. Balance Sheet with assets, liabilities, and equity sections
3. Cash Flow Statement showing operating, investing, and financing activities
4. Key financial ratios (ROI, ROE, Current Ratio, Debt-to-Equity)
5. Charts showing revenue trend, expense breakdown, and cash position
6. Conditional formatting for negative values`,
    expectedInputs: [
      { name: "companyName", type: "text", required: true, label: "Company Name" },
      { name: "period", type: "select", required: true, label: "Reporting Period", options: ["Monthly", "Quarterly", "Annual"] },
      { name: "currency", type: "select", required: false, label: "Currency", defaultValue: "USD", options: ["USD", "EUR", "GBP"] },
      { name: "historicalData", type: "table", required: false, label: "Historical Data (Optional)", description: "Include past periods for trend analysis" }
    ],
    author: "Excel AI Assistant",
    rating: 4.7,
    ratingCount: 98,
    usageCount: 1450,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "advanced",
    estimatedTime: "10 min"
  },
  {
    id: "builtin-004",
    name: "Quick Pivot Analysis",
    description: "Create a pivot table with automatic slicers and recommended layouts",
    category: "analysis",
    tags: ["pivot-table", "analysis", "slicers", "data-exploration"],
    prompt: `Create a pivot table analysis with:
1. Suggested row and column fields based on data types
2. Appropriate aggregation functions (Sum for numbers, Count for text)
3. Slicers for filtering by categorical columns
4. Pivot chart for visualization
5. Conditional formatting on values
6. Subtotals and grand totals`,
    expectedInputs: [
      { name: "dataRange", type: "table", required: true, label: "Data Range" },
      { name: "rowFields", type: "multi-select", required: false, label: "Row Fields (Optional)", description: "Leave empty for auto-detection" },
      { name: "valueField", type: "column", required: false, label: "Values Field (Optional)", description: "Leave empty for auto-detection" }
    ],
    author: "Excel AI Assistant",
    rating: 4.6,
    ratingCount: 134,
    usageCount: 1890,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "beginner",
    estimatedTime: "2 min"
  },
  {
    id: "builtin-005",
    name: "Inventory Tracker",
    description: "Set up an inventory management system with stock levels, reorder alerts, and valuation",
    category: "automation",
    tags: ["inventory", "tracking", "alerts", "management"],
    prompt: `Create an inventory tracking system:
1. Product catalog with SKUs, descriptions, and categories
2. Current stock levels with conditional formatting for low stock
3. Reorder point alerts (highlight when stock < minimum)
4. Inventory valuation (quantity × unit cost)
5. Stock movement log (in/out transactions)
6. Summary dashboard with total items and value`,
    expectedInputs: [
      { name: "productList", type: "table", required: true, label: "Product List", description: "Should include: SKU, Product Name, Category, Unit Cost, Current Stock, Min Stock Level" },
      { name: "enableAlerts", type: "boolean", required: false, label: "Enable Low Stock Alerts", defaultValue: true },
      { name: "valuationMethod", type: "select", required: false, label: "Valuation Method", defaultValue: "FIFO", options: ["FIFO", "LIFO", "Average Cost"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.7,
    ratingCount: 87,
    usageCount: 1120,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "5 min"
  },
  {
    id: "builtin-006",
    name: "Email List Cleaner",
    description: "Validate and clean email lists by removing duplicates, invalid formats, and typos",
    category: "data-cleaning",
    tags: ["email", "cleaning", "validation", "marketing"],
    prompt: `Clean an email contact list:
1. Remove duplicate email addresses
2. Validate email format using regex
3. Flag suspicious domains
4. Extract domain names for analysis
5. Categorize by provider (Gmail, Outlook, Corporate, etc.)
6. Generate statistics on list quality
7. Export clean list to new sheet`,
    expectedInputs: [
      { name: "emailColumn", type: "column", required: true, label: "Email Column" },
      { name: "removeDuplicates", type: "boolean", required: false, label: "Remove Duplicates", defaultValue: true },
      { name: "validateFormat", type: "boolean", required: false, label: "Validate Email Format", defaultValue: true },
      { name: "flagSuspicious", type: "boolean", required: false, label: "Flag Suspicious Domains", defaultValue: true }
    ],
    author: "Excel AI Assistant",
    rating: 4.5,
    ratingCount: 76,
    usageCount: 980,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "beginner",
    estimatedTime: "2 min"
  },
  {
    id: "builtin-007",
    name: "Budget vs Actual Analysis",
    description: "Compare budgeted amounts against actual spending with variance analysis and charts",
    category: "financial",
    tags: ["budget", "variance", "analysis", "finance"],
    prompt: `Create a budget vs actual analysis:
1. Side-by-side comparison of budget vs actual by category
2. Variance calculation ($ and %)
3. Conditional formatting for over-budget items (red)
4. Under-budget highlights (green)
5. Trend chart showing monthly comparison
6. Summary metrics (total budget, actual, variance)
7. Top 5 over-budget categories`,
    expectedInputs: [
      { name: "budgetData", type: "table", required: true, label: "Budget Data", description: "Should include: Category, Budget Amount" },
      { name: "actualData", type: "table", required: true, label: "Actual Spending Data", description: "Should include: Category, Actual Amount, Date" },
      { name: "period", type: "select", required: true, label: "Period", options: ["This Month", "Last Month", "This Quarter", "YTD", "Custom"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.8,
    ratingCount: 112,
    usageCount: 1560,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "4 min"
  },
  {
    id: "builtin-008",
    name: "Project Gantt Chart",
    description: "Generate a Gantt chart for project management with timelines, dependencies, and progress tracking",
    category: "dashboard",
    tags: ["project", "gantt", "timeline", "management"],
    prompt: `Create a project Gantt chart:
1. Task list with start dates, end dates, and durations
2. Visual timeline bars showing task duration
3. Progress bars (%) for each task
4. Milestone markers
5. Dependency arrows between tasks
6. Resource assignment column
7. Color coding by status (Not Started, In Progress, Complete)
8. Critical path highlighting`,
    expectedInputs: [
      { name: "taskList", type: "table", required: true, label: "Task List", description: "Should include: Task Name, Start Date, End Date, Status, Progress %, Assigned To" },
      { name: "showDependencies", type: "boolean", required: false, label: "Show Dependencies", defaultValue: true },
      { name: "timeScale", type: "select", required: false, label: "Time Scale", defaultValue: "days", options: ["days", "weeks", "months"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.6,
    ratingCount: 94,
    usageCount: 1280,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "5 min"
  },
  {
    id: "builtin-009",
    name: "CSV Import Normalizer",
    description: "Automatically detect and fix common CSV import issues like encoding problems, delimiter detection, and column mapping",
    category: "import-export",
    tags: ["csv", "import", "data", "normalization"],
    prompt: `Normalize CSV data import:
1. Auto-detect file encoding (UTF-8, ANSI, etc.)
2. Detect delimiter (comma, semicolon, tab)
3. Handle quoted fields with embedded delimiters
4. Detect and fix header row
5. Map columns to standard names
6. Detect data types for each column
7. Handle missing values appropriately
8. Create import log with issues found`,
    expectedInputs: [
      { name: "csvData", type: "range", required: true, label: "Imported CSV Data" },
      { name: "autoDetectEncoding", type: "boolean", required: false, label: "Auto-detect Encoding", defaultValue: true },
      { name: "delimiter", type: "select", required: false, label: "Delimiter", defaultValue: "auto", options: ["auto", ",", ";", "\\t", "|"] },
      { name: "hasHeaders", type: "boolean", required: false, label: "First Row is Headers", defaultValue: true }
    ],
    author: "Excel AI Assistant",
    rating: 4.4,
    ratingCount: 68,
    usageCount: 890,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "3 min"
  },
  {
    id: "builtin-010",
    name: "KPI Dashboard",
    description: "Create a key performance indicator dashboard with gauges, sparklines, and trend indicators",
    category: "dashboard",
    tags: ["kpi", "dashboard", "metrics", "performance"],
    prompt: `Create a KPI dashboard:
1. Key metric cards with current values and targets
2. Variance indicators (up/down arrows)
3. Sparkline charts for trends
4. Gauges for percentage achievements
5. Traffic light indicators for performance status
6. Comparative metrics (vs last period, vs target)
7. Auto-refresh functionality
8. Print-friendly layout`,
    expectedInputs: [
      { name: "metricsData", type: "table", required: true, label: "Metrics Data", description: "Should include: Metric Name, Current Value, Target Value, Previous Period" },
      { name: "timeRange", type: "select", required: true, label: "Time Range", options: ["Daily", "Weekly", "Monthly", "Quarterly"] },
      { name: "theme", type: "select", required: false, label: "Dashboard Theme", defaultValue: "professional", options: ["professional", "colorful", "minimal", "dark"] }
    ],
    author: "Excel AI Assistant",
    rating: 4.7,
    ratingCount: 145,
    usageCount: 2100,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    version: "1.0",
    isBuiltIn: true,
    isPublic: true,
    difficulty: "intermediate",
    estimatedTime: "6 min"
  }
];

// ============================================================================
// Recipe Service
// ============================================================================

export class RecipeService {
  private static instance: RecipeService;
  private recipes: Map<string, Recipe> = new Map();
  private userRecipes: Map<string, UserRecipe> = new Map();
  private executionHistory: RecipeExecution[] = [];
  private readonly STORAGE_KEY = "excel_ai_recipes";
  private readonly HISTORY_KEY = "excel_ai_recipe_history";

  private constructor() {
    this.loadBuiltInRecipes();
    this.loadUserRecipes();
    this.loadExecutionHistory();
  }

  static getInstance(): RecipeService {
    if (!RecipeService.instance) {
      RecipeService.instance = new RecipeService();
    }
    return RecipeService.instance;
  }

  // ============================================================================
  // Recipe Management
  // ============================================================================

  /**
   * Load built-in recipes into the service
   */
  private loadBuiltInRecipes(): void {
    builtInRecipes.forEach(recipe => {
      this.recipes.set(recipe.id, recipe);
    });
  }

  /**
   * Load user recipes from IndexedDB/localStorage
   */
  private loadUserRecipes(): void {
    try {
      const stored = localStorage.getItem(this.STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        Object.entries(parsed).forEach(([id, recipe]: [string, any]) => {
          this.userRecipes.set(id, {
            ...recipe,
            createdAt: new Date(recipe.createdAt),
            updatedAt: new Date(recipe.updatedAt),
            lastUsed: recipe.lastUsed ? new Date(recipe.lastUsed) : undefined
          });
        });
      }
    } catch (error) {
      logger.error('Failed to load user recipes', { error });
    }
  }

  /**
   * Save user recipes to storage
   */
  private saveUserRecipes(): void {
    try {
      const toStore: Record<string, any> = {};
      this.userRecipes.forEach((recipe, id) => {
        toStore[id] = recipe;
      });
      localStorage.setItem(this.STORAGE_KEY, JSON.stringify(toStore));
    } catch (error) {
      logger.error('Failed to save user recipes', { error });
    }
  }

  /**
   * Load execution history
   */
  private loadExecutionHistory(): void {
    try {
      const stored = localStorage.getItem(this.HISTORY_KEY);
      if (stored) {
        this.executionHistory = JSON.parse(stored).map((e: any) => ({
          ...e,
          executedAt: new Date(e.executedAt)
        }));
      }
    } catch (error) {
      logger.error('Failed to load execution history', { error });
    }
  }

  /**
   * Save execution history
   */
  private saveExecutionHistory(): void {
    try {
      // Keep only last 100 executions
      const trimmed = this.executionHistory.slice(-100);
      localStorage.setItem(this.HISTORY_KEY, JSON.stringify(trimmed));
    } catch (error) {
      logger.error('Failed to save execution history', { error });
    }
  }

  // ============================================================================
  // Recipe CRUD
  // ============================================================================

  /**
   * Get all recipes (built-in + user)
   */
  getAllRecipes(): Recipe[] {
    const allRecipes = [
      ...Array.from(this.recipes.values()),
      ...Array.from(this.userRecipes.values())
    ];
    return allRecipes;
  }

  /**
   * Get recipes with filters
   */
  getRecipes(filters?: RecipeFilters): Recipe[] {
    let results = this.getAllRecipes();

    if (filters) {
      if (filters.category) {
        results = results.filter(r => r.category === filters.category);
      }

      if (filters.tags && filters.tags.length > 0) {
        results = results.filter(r =>
          filters.tags!.some(tag => r.tags.includes(tag))
        );
      }

      if (filters.search) {
        const searchLower = filters.search.toLowerCase();
        results = results.filter(r =>
          r.name.toLowerCase().includes(searchLower) ||
          r.description.toLowerCase().includes(searchLower) ||
          r.tags.some(t => t.toLowerCase().includes(searchLower))
        );
      }

      if (filters.author) {
        results = results.filter(r => r.author === filters.author);
      }

      if (filters.difficulty) {
        results = results.filter(r => r.difficulty === filters.difficulty);
      }

      if (filters.minRating) {
        results = results.filter(r => r.rating >= filters.minRating!);
      }

      if (filters.isBuiltIn !== undefined) {
        results = results.filter(r => r.isBuiltIn === filters.isBuiltIn);
      }

      // Sorting
      if (filters.sortBy) {
        switch (filters.sortBy) {
          case "popular":
            results.sort((a, b) => b.usageCount - a.usageCount);
            break;
          case "newest":
            results.sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime());
            break;
          case "rating":
            results.sort((a, b) => b.rating - a.rating);
            break;
          case "name":
            results.sort((a, b) => a.name.localeCompare(b.name));
            break;
        }
      }
    }

    return results;
  }

  /**
   * Get a single recipe by ID
   */
  getRecipe(id: string): Recipe | undefined {
    return this.recipes.get(id) || this.userRecipes.get(id);
  }

  /**
   * Create a new recipe
   */
  createRecipe(recipeData: Omit<Recipe, "id" | "createdAt" | "updatedAt" | "rating" | "ratingCount" | "usageCount">): Recipe {
    const id = `user-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`;
    const now = new Date();

    const newRecipe: UserRecipe = {
      ...recipeData,
      id,
      rating: 0,
      ratingCount: 0,
      usageCount: 0,
      createdAt: now,
      updatedAt: now,
      useCount: 0
    };

    this.userRecipes.set(id, newRecipe);
    this.saveUserRecipes();

    return newRecipe;
  }

  /**
   * Update an existing recipe
   */
  updateRecipe(id: string, updates: Partial<Recipe>): Recipe | null {
    const recipe = this.userRecipes.get(id);
    if (!recipe) return null;

    const updatedRecipe: UserRecipe = {
      ...recipe,
      ...updates,
      id,
      updatedAt: new Date()
    };

    this.userRecipes.set(id, updatedRecipe);
    this.saveUserRecipes();

    return updatedRecipe;
  }

  /**
   * Delete a recipe
   */
  deleteRecipe(id: string): boolean {
    // Cannot delete built-in recipes
    if (this.recipes.has(id)) return false;

    const deleted = this.userRecipes.delete(id);
    if (deleted) {
      this.saveUserRecipes();
    }
    return deleted;
  }

  /**
   * Duplicate a recipe
   */
  duplicateRecipe(id: string, newName?: string): Recipe | null {
    const original = this.getRecipe(id);
    if (!original) return null;

    const duplicated = this.createRecipe({
      name: newName || `${original.name} (Copy)`,
      description: original.description,
      category: original.category,
      tags: [...original.tags],
      prompt: original.prompt,
      expectedInputs: [...original.expectedInputs],
      previewImage: original.previewImage,
      author: "You",
      authorId: undefined,
      isPublic: false,
      isBuiltIn: false,
      difficulty: original.difficulty,
      estimatedTime: original.estimatedTime,
      version: "1.0"
    });

    // Store reference to original
    const userRecipe = this.userRecipes.get(duplicated.id);
    if (userRecipe) {
      userRecipe.originalRecipeId = id;
      this.saveUserRecipes();
    }

    return duplicated;
  }

  // ============================================================================
  // Recipe Execution
  // ============================================================================

  /**
   * Execute a recipe with given inputs
   */
  async executeRecipe(
    recipeId: string,
    inputs: Record<string, any>,
    workbookName?: string
  ): Promise<RecipeExecutionResult> {
    const startTime = Date.now();
    const recipe = this.getRecipe(recipeId);

    if (!recipe) {
      return {
        success: false,
        message: "Recipe not found",
        error: `Recipe with ID ${recipeId} does not exist`
      };
    }

    // Validate inputs
    const validationErrors: string[] = [];
    for (const input of recipe.expectedInputs) {
      if (input.required && !inputs[input.name]) {
        validationErrors.push(`Missing required input: ${input.label}`);
      }
    }

    if (validationErrors.length > 0) {
      return {
        success: false,
        message: "Validation failed",
        error: validationErrors.join("\n")
      };
    }

    try {
      // Build the execution prompt with user inputs
      const executionPrompt = this.buildExecutionPrompt(recipe, inputs);

      // Simulate execution - in real implementation, this would call AI service
      const result: RecipeExecutionResult = {
        success: true,
        message: `Recipe "${recipe.name}" executed successfully`,
        actions: [
          {
            type: "insert_formula",
            description: "Apply recipe transformations",
            payload: {
              prompt: executionPrompt,
              inputs
            }
          }
        ],
        executionTime: Date.now() - startTime
      };

      // Update usage statistics
      this.incrementUsageCount(recipeId);

      // Record execution
      this.executionHistory.push({
        recipeId,
        recipeName: recipe.name,
        executedAt: new Date(),
        inputs,
        result,
        workbookName
      });
      this.saveExecutionHistory();

      return result;
    } catch (error) {
      return {
        success: false,
        message: "Execution failed",
        error: error instanceof Error ? error.message : "Unknown error",
        executionTime: Date.now() - startTime
      };
    }
  }

  /**
   * Build execution prompt with inputs substituted
   */
  private buildExecutionPrompt(recipe: Recipe, inputs: Record<string, any>): string {
    let prompt = recipe.prompt;

    // Replace input placeholders in prompt
    recipe.expectedInputs.forEach(input => {
      const value = inputs[input.name];
      const placeholder = `{${input.name}}`;
      prompt = prompt.replace(new RegExp(placeholder, "g"), value || "");
    });

    return prompt;
  }

  /**
   * Increment usage count for a recipe
   */
  private incrementUsageCount(recipeId: string): void {
    const recipe = this.recipes.get(recipeId);
    if (recipe) {
      recipe.usageCount++;
    }

    const userRecipe = this.userRecipes.get(recipeId);
    if (userRecipe) {
      userRecipe.usageCount++;
      userRecipe.useCount++;
      userRecipe.lastUsed = new Date();
      this.saveUserRecipes();
    }
  }

  // ============================================================================
  // Ratings & Reviews
  // ============================================================================

  /**
   * Rate a recipe
   */
  rateRecipe(recipeId: string, rating: number, comment?: string): boolean {
    if (rating < 1 || rating > 5) return false;

    const recipe = this.recipes.get(recipeId);
    if (recipe) {
      // Update average rating
      const totalRating = recipe.rating * recipe.ratingCount + rating;
      recipe.ratingCount++;
      recipe.rating = totalRating / recipe.ratingCount;
      return true;
    }

    const userRecipe = this.userRecipes.get(recipeId);
    if (userRecipe) {
      const totalRating = userRecipe.rating * userRecipe.ratingCount + rating;
      userRecipe.ratingCount++;
      userRecipe.rating = totalRating / userRecipe.ratingCount;
      this.saveUserRecipes();
      return true;
    }

    return false;
  }

  // ============================================================================
  // Import / Export
  // ============================================================================

  /**
   * Export recipe to JSON
   */
  exportRecipe(recipeId: string): string | null {
    const recipe = this.getRecipe(recipeId);
    if (!recipe) return null;

    return JSON.stringify(recipe, null, 2);
  }

  /**
   * Import recipe from JSON
   */
  importRecipe(jsonString: string): Recipe | null {
    try {
      const parsed = JSON.parse(jsonString);

      // Validate required fields
      if (!parsed.name || !parsed.description || !parsed.prompt) {
        return null;
      }

      return this.createRecipe({
        name: parsed.name,
        description: parsed.description,
        category: parsed.category || "custom",
        tags: parsed.tags || [],
        prompt: parsed.prompt,
        expectedInputs: parsed.expectedInputs || [],
        previewImage: parsed.previewImage,
        author: "Imported",
        isPublic: false,
        isBuiltIn: false,
        difficulty: parsed.difficulty || "intermediate",
        estimatedTime: parsed.estimatedTime,
        version: parsed.version || "1.0"
      });
    } catch (error) {
      logger.error('Failed to import recipe', { error, jsonData });
      return null;
    }
  }

  /**
   * Share recipe (generate shareable link/data)
   */
  shareRecipe(recipeId: string): string | null {
    const recipe = this.getRecipe(recipeId);
    if (!recipe) return null;

    // Create a compact base64 representation
    const shareData = {
      v: 1,
      n: recipe.name,
      d: recipe.description,
      c: recipe.category,
      t: recipe.tags,
      p: recipe.prompt,
      i: recipe.expectedInputs,
      diff: recipe.difficulty
    };

    return btoa(JSON.stringify(shareData));
  }

  /**
   * Import from share code
   */
  importFromShareCode(shareCode: string): Recipe | null {
    try {
      const decoded = JSON.parse(atob(shareCode));

      return this.createRecipe({
        name: decoded.n,
        description: decoded.d,
        category: decoded.c || "custom",
        tags: decoded.t || [],
        prompt: decoded.p,
        expectedInputs: decoded.i || [],
        previewImage: undefined,
        author: "Shared Recipe",
        authorId: undefined,
        isPublic: false,
        isBuiltIn: false,
        difficulty: decoded.diff || "intermediate",
        estimatedTime: undefined,
        version: "1.0"
      });
    } catch (error) {
      logger.error('Failed to import from share code', { error, shareCode });
      return null;
    }
  }

  // ============================================================================
  // Statistics & Analytics
  // ============================================================================

  /**
   * Get execution history
   */
  getExecutionHistory(limit?: number): RecipeExecution[] {
    const sorted = [...this.executionHistory].sort(
      (a, b) => b.executedAt.getTime() - a.executedAt.getTime()
    );
    return limit ? sorted.slice(0, limit) : sorted;
  }

  /**
   * Get frequently used recipes
   */
  getFrequentlyUsedRecipes(limit: number = 5): Recipe[] {
    return this.getAllRecipes()
      .sort((a, b) => b.usageCount - a.usageCount)
      .slice(0, limit);
  }

  /**
   * Get recently used recipes
   */
  getRecentlyUsedRecipes(limit: number = 5): UserRecipe[] {
    return Array.from(this.userRecipes.values())
      .filter(r => r.lastUsed)
      .sort((a, b) => (b.lastUsed?.getTime() || 0) - (a.lastUsed?.getTime() || 0))
      .slice(0, limit);
  }

  /**
   * Get category distribution
   */
  getCategoryDistribution(): Map<RecipeCategory, number> {
    const distribution = new Map<RecipeCategory, number>();

    this.getAllRecipes().forEach(recipe => {
      const count = distribution.get(recipe.category) || 0;
      distribution.set(recipe.category, count + 1);
    });

    return distribution;
  }

  /**
   * Get all available tags
   */
  getAllTags(): string[] {
    const tags = new Set<string>();
    this.getAllRecipes().forEach(recipe => {
      recipe.tags.forEach(tag => tags.add(tag));
    });
    return Array.from(tags).sort();
  }

  // ============================================================================
  // Categories
  // ============================================================================

  /**
   * Get category display name
   */
  getCategoryDisplayName(category: RecipeCategory): string {
    const displayNames: Record<RecipeCategory, string> = {
      "data-cleaning": "Data Cleaning",
      "reporting": "Reporting",
      "analysis": "Analysis",
      "formatting": "Formatting",
      "financial": "Financial",
      "dashboard": "Dashboard",
      "import-export": "Import/Export",
      "automation": "Automation",
      "custom": "Custom"
    };

    return displayNames[category] || category;
  }

  /**
   * Get all categories
   */
  getAllCategories(): { key: RecipeCategory; name: string }[] {
    const categories: RecipeCategory[] = [
      "data-cleaning",
      "reporting",
      "analysis",
      "formatting",
      "financial",
      "dashboard",
      "import-export",
      "automation",
      "custom"
    ];

    return categories.map(cat => ({
      key: cat,
      name: this.getCategoryDisplayName(cat)
    }));
  }
}

// Export singleton instance
export const recipeService = RecipeService.getInstance();
export default recipeService;
